### ISSUE TITLE
fix: 새 밋팀 생성 멤버 삭제 버그

### ISSUE THREAD

**Issue by prgmr99** [MeeTeamNumdle/MeeTeam_FrontEnd#20]
## Bug Issues
- 삭제 로직에는 문제가 없음.
- 컴포넌트 삭제가 정상적이지 않음.
- 컴포넌트가 담긴 배열을 보면 정확하게 삭제가 되는 것을 확인할 수 있음.
- 컴포넌트 속에 담긴 드롭다운이 컴포넌트와 무관하게 삭제됨.

**Comment by kimsuyeon0916** [comment]
승준님 여기 이슈 템플릿이 적용이 안된 것 같습니다..!

**Comment by prgmr99** [comment]
> 승준님 여기 이슈 템플릿이 적용이 안된 것 같습니다..!

아하..!! 그렇네요.. 이게 #7번 이슈의 task에서 바로 이슈를 생성해버리니까 템플릿이 없이 생성되네요..!!
추가해놓겠습니다!
