### ISSUE TITLE
fix: 디자인 및 변경사항 수정

### ISSUE THREAD

**Issue by prgmr99** [MeeTeamNumdle/MeeTeam_FrontEnd#49]
## Feature Issues
- 기획, 디자인 수정사항(240129, 240201) 반영하기

## To Do
- [x] 헤더: 아이콘 파일 분리
- [x] 새 밋팀 생성 페이지: 멤버 카드 수정(임시), 모달창 배경 스크롤 방지 및 어둡게 수정
- [x] 밋팀 관리 목록 페이지: 내 활동 위치 이동 및 레이아웃 수정(사이드바 추가)
- [x] 밋팀 관리 목록 페이지: 포트폴리오 페이지(핀, 설명 추가)
- [x] 구인 글 등록 페이지: 멤버 부분 제거
- [ ] 구인 글 등록 페이지: 역할&스펙 및 인원 폼 추가(디자인 필요) 
- [ ] 산출물 등록 페이지: 이미지(최대 10개)  등록할 수 있는 공간 생성 -> 드래그 마지막에 작업
- [x] 산출물 등록 페이지: 링크(최대 4개) 등록할 수 있는 공간 생성
- [ ] 구인 게시판 페이지 
    - [x] 구인 밋팀 -> 구인 게시판
    - [x] 정렬 기능(최신순 / 마감일순 / 북마크순)
    - [x] 조회수 제거
    - [x] 북마크 추가
    - [ ] 태그 필터링 구현
    - [ ] 수업만 보기(체크박스)
    - [x] 추천 4개만
    - [x] 페이지네이션 구현(한 페이지 24개 / 최대 10 페이지)
- [x] 특정 구인 글 상세 페이지: 
    - [x] 텍스트 수정(신청하기, 비슷한 구인 글), 컨텐츠 수정
    - [x] 지원하기 제거
    - [x] 태그 제거
    - [x] 댓글 클릭 시,로그인이 안 되었을 경우 팝업 -> 입력창에 로그인 필요하다고 하고, 클릭 시 로그인 창으로 이동
    - [x] 북마크 기능 추가
    - [x] 신청하기 중 취소하기 추가
    - [x] 응답률 UI 추가
    - [x] 마감일 사이렌 추가
    - [x] 대댓글 기능 구현
- [x] 내 활동 페이지 작업
    - [x] 신청한 구인 글 페이지
    - [x] 북마크한 구인 글 페이지
    - [ ] 구인 글 카드 디자인 수정
- [ ] 산출물 등록 미리보기 페이지
- [ ] 유저 목록 페이지
- [ ] 새 밋팀 생성 페이지/산출물 등록 페이지: 버그 수정

**Comment by kimsuyeon0916** [comment]
저도 이렇게 미리 정리해놔야겠군요..! 깔꼼하네요
